name: Update Package Versions

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: "0 0 * * 0"  # Schedule to run every Sunday at midnight UTC (optional)

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List .txt files
        run: |
          # Use the find command to list all .txt files
          find . -type f -name "*.py" > file_paths.txt
          
          # Display the content of the file_paths.txt for verification
          cat file_paths.txt

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          pip install requests
          # Add any other dependencies here if needed

      - name: Make script executable
        run: |
          cd scripts/fdroid_repo/
          ls  # List the contents of the directory to verify the presence of the script
          chmod +x fdroid_repo_parser.py
        working-directory: scripts/fdroid_repo/


      - name: Run Python Script
        run: |
          python scripts/fdroid_repo/fdroid_repo_parser.py  # Replace 'your_script.py' with the actual filename
        working-directory: scripts/fdroid_repo/  # Specify the directory where your script is located

      - name: Copy file to repository
        run: |
          mkdir -p ../../app/src/main/res/xml/
          cp package_versions.xml ../../app/src/main/res/xml/
        working-directory: scripts/fdroid_repo  # Specify the directory where your script is located

      - name: Commit and push changes
        run: |
          git add ../../app/src/main/res/xml/package_versions.xml
          git commit -m "Update package versions"
          git push https://${{ secrets.TOKEN }}@github.com/Hamza417/Inure.git

      - name: Delete repository metadata files
        run: |
          rm -f fdroid_index.xml
          rm -f izzyondroid_index.xml
        working-directory: scripts/fdroid_repo/  # Specify the directory where your script is located
